/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poncecristianproject;

/**
 *
 * @author cristian_ponce
 */
public class IntroFrame extends javax.swing.JFrame {

    Parent father;
    Parent mother;

    /**
     * Creates new form introFrame
     */
    public IntroFrame() {
        initComponents();
    }

    public IntroFrame(Parent father, Parent mother) {
        initComponents();
        this.father = father;
        this.mother = mother;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameBackground = new javax.swing.JPanel();
        frameTitle = new javax.swing.JLabel();
        authorNote = new javax.swing.JLabel();
        dnaImage = new javax.swing.JLabel();
        descriptionLabelOne = new javax.swing.JLabel();
        descriptionLabelTwo = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        frameBackground.setBackground(new java.awt.Color(153, 153, 255));

        frameTitle.setFont(new java.awt.Font("Lao Sangam MN", 0, 24)); // NOI18N
        frameTitle.setForeground(new java.awt.Color(255, 255, 255));
        frameTitle.setText("Welcome to Genetic Risk Advisor!");

        authorNote.setFont(new java.awt.Font("Lao Sangam MN", 0, 13)); // NOI18N
        authorNote.setForeground(new java.awt.Color(255, 255, 255));
        authorNote.setText("Cristian Ponce ITSC 1213 Final (2020)");

        dnaImage.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/poncecristianproject/dna.png"))); // NOI18N
        dnaImage.setEnabled(false);

        descriptionLabelOne.setFont(new java.awt.Font("Lao Sangam MN", 0, 13)); // NOI18N
        descriptionLabelOne.setForeground(new java.awt.Color(255, 255, 255));
        descriptionLabelOne.setText("This program takes the screening results of prospective parents to determine the risk");

        descriptionLabelTwo.setFont(new java.awt.Font("Lao Sangam MN", 0, 13)); // NOI18N
        descriptionLabelTwo.setForeground(new java.awt.Color(255, 255, 255));
        descriptionLabelTwo.setText("of a future child being impacted by a genetic disorder.");

        nextButton.setFont(new java.awt.Font("Lao Sangam MN", 0, 13)); // NOI18N
        nextButton.setText("Continue to Parent Surveys ->");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameBackgroundLayout = new javax.swing.GroupLayout(frameBackground);
        frameBackground.setLayout(frameBackgroundLayout);
        frameBackgroundLayout.setHorizontalGroup(
            frameBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameBackgroundLayout.createSequentialGroup()
                .addGroup(frameBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameBackgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(dnaImage, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frameBackgroundLayout.createSequentialGroup()
                        .addGroup(frameBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(frameBackgroundLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(frameTitle))
                            .addGroup(frameBackgroundLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(descriptionLabelOne)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(frameBackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(frameBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(frameBackgroundLayout.createSequentialGroup()
                                .addComponent(descriptionLabelTwo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(frameBackgroundLayout.createSequentialGroup()
                                .addComponent(authorNote)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nextButton)))))
                .addContainerGap())
        );
        frameBackgroundLayout.setVerticalGroup(
            frameBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameBackgroundLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(frameTitle)
                .addGap(18, 18, 18)
                .addComponent(dnaImage, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(descriptionLabelOne, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionLabelTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(frameBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorNote)
                    .addComponent(nextButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 532, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        SurveyFrame survey = new SurveyFrame(father, mother, true);
        survey.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nextButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorNote;
    private javax.swing.JLabel descriptionLabelOne;
    private javax.swing.JLabel descriptionLabelTwo;
    private javax.swing.JLabel dnaImage;
    private javax.swing.JPanel frameBackground;
    private javax.swing.JLabel frameTitle;
    private javax.swing.JButton nextButton;
    // End of variables declaration//GEN-END:variables
}
